-- 0001_init.sql
-- Phase 1 (core) schema: properties, owners, documents, guests, bookings,
-- compliance tasks, audit log. Written as hand-authored SQL (rather than
-- generated by an ORM migration tool) so it runs identically against the
-- embedded PGlite database used for local dev/test and against a managed
-- Postgres instance (e.g. Supabase) in production.

-- gen_random_uuid() is built into Postgres core since v13; no pgcrypto needed.
CREATE EXTENSION IF NOT EXISTS btree_gist; -- exclusion constraint on booking

-- ---------- enums ----------
DO $$ BEGIN
  CREATE TYPE app_role AS ENUM ('owner','manager','finance','housekeeping','maintenance','readonly');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE property_status AS ENUM ('active','inactive','maintenance','being_sold');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE det_classification AS ENUM ('standard','deluxe');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE document_type AS ENUM (
    'title_deed','tenancy_contract','ejari','landlord_noc','building_noc',
    'det_permit','trade_licence','insurance_policy','utility_contract',
    'inspection_certificate','owner_id','other');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE document_owner_type AS ENUM ('property','owner','guest','booking');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE guest_document_type AS ENUM ('passport','emirates_id','gcc_national_id');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE booking_status AS ENUM (
    'enquiry','tentative','confirmed','checked_in','checked_out','cancelled','no_show');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE compliance_task_type AS ENUM ('guest_registration','permit_renewal');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE compliance_task_status AS ENUM ('pending','done','overdue');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------- tables ----------
CREATE TABLE IF NOT EXISTS app_user (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  name text NOT NULL,
  password_hash text NOT NULL,
  role app_role NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS owner (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  id_type text,
  id_number text,
  nationality text,
  mobile text,
  email text,
  address text,
  bank_details text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS property (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reference_code text NOT NULL UNIQUE,
  name text NOT NULL,
  unit_number text,
  building text,
  community text,
  area text,
  emirate text NOT NULL DEFAULT 'Dubai',
  bedrooms integer NOT NULL CHECK (bedrooms >= 0),
  bathrooms integer NOT NULL CHECK (bathrooms >= 0),
  max_occupancy integer NOT NULL CHECK (max_occupancy >= 1),
  size_sqft numeric,
  floor text,
  view text,
  furnishing_status text,
  classification det_classification NOT NULL DEFAULT 'standard',
  status property_status NOT NULL DEFAULT 'active',
  owner_id uuid REFERENCES owner(id),
  door_access_note text,
  wifi_network text,
  wifi_password text,
  amenities jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS property_photo (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL REFERENCES property(id) ON DELETE CASCADE,
  url text NOT NULL,
  caption text,
  room_tag text,
  sort_order integer NOT NULL DEFAULT 0,
  is_cover boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS utility_account (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL REFERENCES property(id) ON DELETE CASCADE,
  type text NOT NULL,
  provider text,
  account_number text,
  premise_number text,
  billing_cycle text,
  avg_monthly_cost numeric,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS guest (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  nationality text,
  dob date,
  gender text,
  document_type guest_document_type,
  document_number text,
  document_issuing_country text,
  document_expiry date,
  document_file_url text,
  mobile text,
  email text,
  whatsapp text,
  address text,
  notes text,
  verified boolean NOT NULL DEFAULT false,
  vip boolean NOT NULL DEFAULT false,
  blocked boolean NOT NULL DEFAULT false,
  blocked_reason text,
  consent_given_at timestamptz,
  consent_version text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS document (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type document_type NOT NULL,
  owner_type document_owner_type NOT NULL,
  property_id uuid REFERENCES property(id) ON DELETE CASCADE,
  owner_record_id uuid REFERENCES owner(id) ON DELETE CASCADE,
  guest_id uuid REFERENCES guest(id) ON DELETE CASCADE,
  booking_id uuid,
  reference_number text,
  issuer text,
  issue_date date,
  expiry_date date,
  file_url text,
  uploaded_by uuid REFERENCES app_user(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS booking (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_number text NOT NULL UNIQUE,
  property_id uuid NOT NULL REFERENCES property(id),
  lead_guest_id uuid NOT NULL REFERENCES guest(id),
  source_channel text NOT NULL DEFAULT 'direct',
  check_in date NOT NULL,
  check_out date NOT NULL CHECK (check_out > check_in),
  adults integer NOT NULL DEFAULT 1 CHECK (adults >= 0),
  children integer NOT NULL DEFAULT 0 CHECK (children >= 0),
  infants integer NOT NULL DEFAULT 0 CHECK (infants >= 0),
  occupied_bedrooms integer NOT NULL DEFAULT 1 CHECK (occupied_bedrooms >= 1),
  status booking_status NOT NULL DEFAULT 'enquiry',
  hold_expires_at timestamptz,
  det_registration_status text NOT NULL DEFAULT 'not_required',
  notes text,
  compliance_override_by uuid REFERENCES app_user(id),
  compliance_override_reason text,
  -- generated column used only by the exclusion constraint below
  stay_range daterange GENERATED ALWAYS AS (daterange(check_in, check_out, '[)')) STORED,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  -- The core anti-double-booking guarantee: no two bookings on the same
  -- property with overlapping stay ranges may both hold an
  -- occupancy-blocking status. Tentative holds, cancellations and enquiries
  -- do not block, matching spec section 4.4's booking rules.
  CONSTRAINT booking_no_overlap EXCLUDE USING gist (
    property_id WITH =,
    stay_range WITH &&
  ) WHERE (status IN ('confirmed','checked_in'))
);

CREATE TABLE IF NOT EXISTS booking_occupant (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL REFERENCES booking(id) ON DELETE CASCADE,
  guest_id uuid NOT NULL REFERENCES guest(id),
  is_lead boolean NOT NULL DEFAULT false,
  det_submission_status text NOT NULL DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS compliance_task (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type compliance_task_type NOT NULL,
  property_id uuid REFERENCES property(id) ON DELETE CASCADE,
  booking_id uuid REFERENCES booking(id) ON DELETE CASCADE,
  due_at timestamptz NOT NULL,
  status compliance_task_status NOT NULL DEFAULT 'pending',
  completed_at timestamptz,
  reference text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  before jsonb,
  after jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_booking_property ON booking(property_id);
CREATE INDEX IF NOT EXISTS idx_document_property ON document(property_id);
CREATE INDEX IF NOT EXISTS idx_document_expiry ON document(expiry_date);
CREATE INDEX IF NOT EXISTS idx_compliance_task_due ON compliance_task(due_at);
CREATE INDEX IF NOT EXISTS idx_guest_email ON guest(email);
